version: '3'

services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "0.0.0.0:9000:9000"
      - "0.0.0.0:9001:9001"
    volumes:
      - minio_data:/data
      - minio_cfg_data:/root/.minio
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_BROWSER_LANGUAGE: "zh-CN" 
      MINIO_SERVER_URL: "http://0.0.0.0:9000"
      MINIO_BROWSER_REDIRECT_URL: "http://0.0.0.0:9001"
    command: server /data --console-address ":9001" --address ":9000"
    restart: always

  # MySQL 数据库
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - default-network
    restart: always

  # Redis 缓存
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - default-network
    restart: always

  # Eureka 服务注册中心
  eureka:
    build: .  # 使用当前目录的 Dockerfile 构建镜像
    container_name: eureka
    ports:
      - "8761:8761"
    networks:
      - default-network
    depends_on:
      - mysql
      - redis
    restart: always

  # zk
  zookeeper:
    image: zookeeper:3.7
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zookeeper:2888:3888;2181
    volumes:
      - ./zk-data:/data
      - ./zk-datalog:/datalog
    networks:
      - default-network
    restart: always

networks:
  default-network:
    driver: bridge

volumes:
  mysql_data:
  redis_data:
  minio_data:
  minio_cfg_data: