server:
  port: 8084

spring:
  application:
    name: dubbo-provider

dubbo:
  application:
    name: ${spring.application.name}
    qos-enable: true
    qos-port: 22223
    qos-accept-foreign-ip: false
  protocol:
    name: dubbo
    port: 20881
  registry:
    address: zookeeper://192.168.3.111:2181
  config-center:
    address: zookeeper://192.168.3.111:2181
  metadata-report:
    address: zookeeper://192.168.3.111:2181 