server:
  port: 8082

spring:
  application:
    name: dubbo-consumer

dubbo:
  application:
    name: ${spring.application.name}
  registry:
    address: zookeeper://192.168.3.111:2181
  config-center:
    address: zookeeper://192.168.3.111:2181
  metadata-report:
    address: zookeeper://192.168.3.111:2181
  consumer:
    check: false 